### ISSUE TITLE
Prerequisite Search

### ISSUE THREAD

**Issue by brianadouglas** [venkatesh-sivaraman/FireRoad-Android#3]
After clicking on 'View Subjects with [subject number] as prerequisite', the search incorrectly returns nothing in the cases of 8.01 and 18.01, among others.

**Comment by liuric** [comment]
The prereq search for some reason used the toString() (which resulted in "calculus") method instead of the rawValue ("gir:calc2") field, which was what was listed for the prereqs strings for each course. The separation of GIR courses that were equivalent and rest and lab courses didn't filter out lab courses. 
I pushed these fixes in the prereq-search-bugfix branch, but the relevance of the courses are probably not correct, resulting in a weird order for the search results.

**Comment by venkatesh-sivaraman** [comment]
Resolved by #6
